url: "https://www.danhorst.com"

keep_files:
  - assets

kramdown:
  parse_block_html: true
title: "Dan Brubaker Horst"
timezone: America/Indiana/Indianapolis

feed:
  collections:
    writing:
      path: /feed

collections:
  writing:
    output: true
    permalink: /writing/:slug/
    sort_field: "date"
    sort_direction: "descending"
  lists:
    output: true
    permalink: /lists/:slug/
  food:
    output: true
    permalink: /food/:slug/
  rum:
    output: true
    permalink: /rum/:slug/
    sort_field: "date"
  health:
    output: true
    permalink: /health/:slug/
    sort_field: "date"
