baseURL =  "https://www.danhorst.com/"
disableLiveReload = true
enableEmoji = true
languageCode = "en-us"
pagination.pagerSize = 500
pluralizelisttitles = false
title = "Dan Brubaker Horst"

[params]
  author = "Dan Brubaker Horst"

[frontmatter]
  date  = [":filename", ":default"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
 
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "max-age=31536000,public,must-revalidate"
