baseURL =  "https://www.danhorst.com/"
languageCode =  "en-us"
title = "Dan Brubaker Horst"
paginate = 500
disableLiveReload = true
pluralizelisttitles = false

[params]
  author = "Dan Brubaker Horst"

[frontmatter]
  date  = [":filename", ":default"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
