[build]
publish = "output"
command = "npm install && npm run esbuild && bundle exec bridgetown build"

[[headers]]
  for = "/feed"
  [headers.values]
    Content-Type = "application/atom+xml; charset=utf-8"

[[redirects]]
  from   = "/feed/"
  to     = "/feed"
  status = 301

[[headers]]
  for = "/font/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.txt"
  [headers.values]
    Content-Type = "text/markdown; charset=utf-8"

[[headers]]
  for = "/:section/*.txt"
  [headers.values]
    Content-Type = "text/markdown; charset=utf-8"

[build.environment]
RUBY_VERSION = "4.0.2"
BUNDLE_VERSION = "4.0.9"

[context.deploy-preview]
command = "npm install && npm run esbuild && bundle exec bridgetown build"
